apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: voter-service-mysql
  labels:
    app: voter-service-mysql
spec:
  selector:
    matchLabels:
      app: voter-service-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: voter-service-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7.22
        name: mysql
        env:
        - name: MYSQL_USER
          value: skaioskit
        - name: MYSQL_DATABASE
          value: voter
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: skaioskit-voter-service-mysql-root-password
              key: value
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: skaioskit-voter-service-mysql-password
              key: value
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        hostPath:
          path: "${DIR}/working/mysql"
---
kind: Service
apiVersion: v1
metadata:
  name: voter-service-mysql
spec:
  selector:
    app: voter-service-mysql
  ports:
  - protocol: TCP
    port: 3306
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: voter-service
  labels:
    app: voter-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: voter-service
    spec:
      containers:
      - name: voter-service
        image: localhost:5000/skaioskit/voter-service:latest
        imagePullPolicy: Always
        command: 
        - /voter
        - serve
        ports:
        - containerPort: 80
        env:
        - name: BUILD_DATETIME
          value: "${DATETIME}"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: skaioskit-jwt-secret
              key: value
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: skaioskit-voter-service-mysql-password
              key: value
        volumeMounts:
        - name: log-storage
          mountPath: /logs
      volumes:
      - name: log-storage
        hostPath:
          path: "${DIR}/working/logs"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: voter-service-ensure-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: voter-service-ensure
            image: localhost:5000/skaioskit/voter-service:latest
            imagePullPolicy: Always
            command: 
            - /voter
            - ensure
            env:
            - name: BUILD_DATETIME
              value: "${DATETIME}"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: skaioskit-jwt-secret
                  key: value
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skaioskit-voter-service-mysql-password
                  key: value
            volumeMounts:
            - name: voter-data-dir
              mountPath: /data
          volumes:
          - name: voter-data-dir
            hostPath:
              path: "${DIR}/data"
          restartPolicy: OnFailure
---
kind: Service
apiVersion: v1
metadata:
  name: voter-service
spec:
  selector:
    app: voter-service
  ports:
  - protocol: TCP
    port: 80
---
